### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by dgilperez** [asd-xiv/m#10]
I was wondering how to use `sort` / `sortBy` to sort by dates, which I believe is a common use case. I was about to open a PR but wanted to check your opinion first. 

This is what I have, for sorting objects by a given field:

```js
const sortByDate = field =>
  sort((a, b) => {
    if (isEmpty(b[field])) {
      return -1
    }

    if (isEmpty(a[field])) {
      return 1
    }

    return new Date(b[field]).getTime() - new Date(a[field]).getTime()
  })
```

which in turn takes me to consider other sorting behaviors (alphabetical?) and also if you'd add a new file for each sorting, or maybe generalize the criterium ...

**Comment by andreidmt** [comment]
Yeah, the sorting capabilities are lacking at this point. Nice wrapper btw!

Here's how I see it:

1. Rewrite `sort` only for primitives: `sort(direction = "asc", source)`
2. Add `sortBy` to use a custom transform function: `sortBy(fn, source)`
3. Rewrite `sortWith` to use an object with fields on which to sort on:

- Multiple fields with explicit directions

```js
sortWith({
  "isActive": "desc",
  "position": "asc",
})
```

- Field with custom transform and explicit direction

```js
sortWith({
  "createdAt": [source => new Date(source).getTime(), "desc"]
})
```

- Field with custom transform and default direction

```js
sortWith({
  "createdAt": source => new Date(source).getTime()
})
```

- Multiple fields with combined formats

```js
sortWith({
  "isActive": "desc",
  "createdAt": source => new Date(source).getTime()
})
```
